const beginnerDict = {
	"Diligent": "Constant and earnest in effort and application",
	"Whimsical": "Playful or out of the ordinary",
	"Abnormal": "Different from what is normal or usual, typically in a way that is undesirable",
	"Abrupt": "Sudden and unexpected",
	"Accelerate": "(Of a vehicle or other physical object) Begin to move more quickly; Increase in amount or extent",
	"Acknowledge": "Accept or admit the existence or truth of",
	"Acquire": "Buy or obtain (an asset or object) for oneself",
	"Aspire": "Direct one's hopes or ambitions toward achieving something",
	"Addictive": "(Of a substance, thing, or activity) Causing or likely to cause someone to become very loving/loyal to",
	"Agitate": "To make (someone) troubled or nervous",
	"Anonymous": "(Of a person) Not identified by name",
	"Plead": "To beg emotionally",
	"Brawl": "A rough or noisy fight or quarrel",
	"Browse": "To look through casually",
	"Endure": "To carry on through, despite hardships",
	"Flaw": "A mark, fault, or other imperfection that marks a substance or object",
	"Grim": "Forbidding or uninviting",
	"Gruesome": "Extremely unpleasant",
	"Consult": "To seek information or advice from (someone with expertise)",
	"Dumbfounded": "To be greatly astonished or surprised",
	"Hilarious": "Extremely funny and amusing",
	"Incident": "An event or occurrence (Note: This word is usually used in a negative way for an event or occurrence)",
	"Infuriate": "To make (someone) extremely angry and impatient",
	"Intense": "(Of a condition, quality, feeling) Existing in a high degree",
	"Loathe": "To dislike greatly and often with disgust or intolerance",
	"Quench": "To satisfy (one's thirst) by drinking",
	"Independent": "Not relying on others for support, care, or funds",
	"Neglect": "To pay little or no attention to",
	"Noteworthy": "Interesting, significant, or unusual",
	"Overwhelmed": "Overpowering the thoughts, emotions, or senses of",
	"Permanent": "Continuing/lasting with no change",
	"Persist": "To continue on despite difficulty, opposition or failure",
	"Ponder": "To think about (something) carefully, especially before deciding or concluding",
	"Resume": "Begin to do or pursue (something) again after a pause or interruption",
	"Simultaneously": "Happening, existing, or done at the same time",
	"Uncertain": "Not completely confident or sure of something",
	"Vicious": "Very cruel or violent",
	"Yearn": "To have an intense feeling of loss or lack and longing for something",
	"Generous": "Showing kindness towards others",
	"Indulge": "To give into freely, especially in one's desires",
	"Unique": "One of a kind, Original",
	"Reluctant": "Unwilling and hesitant",
	"Flattered": "To feel pleased and complimented",
	"Delighted": "Feeling or showing great pleasure",
	"Befriend": "To become friends with",
	"Recognize": "Identify (someone or something) from having encountered them before",
	"Consequence": "A result or effect of an action or condition",
	"Random": "Having no specific pattern, purpose, or objective",
	"Distinctive": "Characteristic of one person or thing, and so serving to distinguish it from others",
	"Influence": "The ability to have an effect on the character, development, or behavior of someone or something, or the effect itself.",
	"Terrible": "Extremely and shockingly or distressingly bad or serious",
	"Fantastic": "Great; Wonderful; Of extraordinary size or degree",
	"Honorable": "Bringing or worthy of honor/respect",
	"Abandon": "Give up completely (a course of action, a practice, or a way of thinking); To leave behind",
	"Paradise": "A place of ideal beauty or loveliness",
	"Magnificent": "Impressively beautiful, elaborate, or extravagant; striking; Very good; excellent.",
	"Energetic": "Showing or involving great activity or vitality",
	"Insist": "To demand something forcefully, not accepting refusal",
	"Passion": "Strong and barely controllable emotion; A state or outburst of such emotion",
	"Variety": "The quality or state of being different or diverse; the absence of uniformity, sameness, or monotony",
	"Compromise": "An agreement or a settlement of a dispute that is reached by each side making concessions.",
	"Beneficial": "Receiving or entitling one to receive advantage, use, or benefit",
	"Corrupt": "Marked by immorality; Dishonest; Containing errors or alterations",
	"Arrogant": "Believing to be superior to others; Having or revealing an exaggerated sense of one's own importance or abilities",
	"Impulsive": "Acting or doing something without thinking things through",
	"Narrator": "A person who delivers a commentary accompanying a movie, broadcast, piece of music and so on",
	"Eliminate": "To completely remove or get rid of (something)",
	"Stubborn": "Having or showing determination not to change one's attitude or position on something, especially in spite of good arguments or reasons",
	"Provoke": "Stimulate or give rise to a reaction or emotion in someone",
	"Exclude": "Deny (someone) access to a place, group, or privilege; Keep (something) out of a place.",
	"Reputation": "A widespread belief that someone or something has a particular habit or characteristic",
	"Urgent": "(Of a state or situation) Requiring immediate action or attention",
	"Tempt": "Have an urge or inclination to do something",
	"Clarify": "To make (a statement or situation) less confusing and more understandable",
	"Confess": "To admit or state that one has committed a crime or is at fault in some way; Admit or acknowledge something reluctantly",
	"Justice": "Honorable/right behavior or treatment; The quality of being fair and reasonable",
	"Donation": "The act of giving to a fund or cause; A gift or grant",
	"Modify": "To make minor changes to (something), typically so as to improve it or to make it less extreme",
	"Adorable": "Very cute, lovable",
	"Spectacular": "Impressive in appearance or thrilling in effect; Incredible; Wonderful",
	"Outrageous": "Shockingly bad; Extremely unusual or unconventional",
	"Innocent": "Not guilty of a crime or offense; Ignorant (in a good way)",
	"Commence": "To begin, to start",
	"Mystery": "Something that is difficult or impossible to understand or explain",
	"Deplete": "Use up the supply of; exhaust the abundance of",
	"Humble": "Having or showing a modest or low estimate of one's own importance",
	"Dominant": "Most important, powerful, or influential",
	"Ridiculous": "Deserving mockery; Absurd; Laughable; Crazy; Weird",
	"Consistent": "(Of a person, behavior, or process) Unchanging in achievement or effect over a period of time",
	"Sensitive": "Quick to take offense, touchy; Or, responsive to or aware of feelings, moods, reactions and so on",
	"Threat": "A statement of an intention to inflict pain, injury, damage, or other hostile action on someone in retribution for something done or not",
	"Express": "Convey (a thought or feeling) in words or by gestures and conduct; To show off",
	"Evaluate": "Form an idea of the amount, number, or value of; Assess",
	"Disturb": "Interfere with the normal arrangement or functioning of; Destroy the sleep or relaxation of",
	"Verify": "Make sure or demonstrate that (something) is true, accurate, or justified",
	"Complicated": "Make (something) more difficult or confusing by causing it to be more complex",
	"Significant": "Sufficiently great or important to be worthy of attention; Noteworthy",
	"Comprehend": "Grasp mentally; Understand",
	"Curious": "Eager to know or learn something",
	"Characteristic": "A feature or quality belonging typically to a person, place, or thing and serving to identify it",
	"Character": "The mental and moral qualities distinctive to an individual; The distinctive nature of something",
	"Precise": "Marked by exactness and accuracy of expression or detail; (Of a person) Exact, accurate, and careful about details",
	"Logical": "Of or according to the rules of logic or formal argument; Characterized by clear, sound reasoning",
	"Necessary": "Required to be done, achieved, or present; essential",
	"Inspire": "Fill (someone) with the urge or ability to do or feel something",
	"Sociable": "Willing to talk and engage in activities with other people; friendly",
	"Exaggerate": "Represent (something) as being larger, greater, better, or worse than it really is",
	"Obvious": "Easily perceived or understood",
	"Fascinating": "Extremely interesting",
	"Studious": "Spending a lot of time studying or reading",
	"Embarrassed": "To cause to feel self- conscious or ill at ease",
	"Sufficient": "Enough; Adequate",
	"Weary": "Feeling or showing tiredness, especially as a result of excessive exertion or lack of sleep",
	"Wary": "Feeling or showing caution about possible dangers or problems",
	"Exhausted": "Drained of one's physical or mental resources",
	"Enhance": "Intensify, increase, or further improve the quality, value, or extent of",
	"Intriguing": "Arouse the curiosity or interest of; Fascinate",
	"Affectionate": "Readily feeling or showing fondness or tenderness; Expressing fondness",
	"Anticipate": "Regard as probable; Expect or predict",
	"Analyze": "Examine methodically and in detail the constitution or structure of (something, especially information)",
	"Literally": "In a literal manner or sense",
	"Tolerant": "Showing willingness to allow the existence of opinions or behavior that one does not necessarily agree with",
	"Ambitions": "A strong desire to do or to achieve something, typically requiring determination and hard work",
	"Ambitious": "Having or showing a strong desire and determination to succeed",
	"Anxious": "Experiencing worry, unease, or nervousness, typically about an imminent event or something with an uncertain outcome",
	"Chaotic": "In a state of complete confusion and disorder",
	"Eager": "Wanting to do or have something very much"
}
module.exports = beginnerDict;