const intermediateDict = {
	"consensus": "A collective or general agreement of opinion, feeling, or thinking",
	"taint": "a stain or spot; a mark of corruption or dishonor; to stain or contaminate",
	"hailed": "greeted",
	"apparently": "seemingly",
	"aplomb": "self-confidence",
	"impose": "to force on somebody",
	"tactical": "A style of management that is directive and controlling",
	"discourse": "to communicate thoughts orally; talk; converse",
	"defy": "challenge authority or power",
	"verdict": "A decision or judgment",
	"perceive": "to see or understand",
	"alter": "Angry dispute; noisy quarrel",
	"prompt": "On time; done without delay",
	"regime": "a government in power; a form or system of rule or management; a period of rule",
	"delight": "a feeling of extreme pleasure or satisfaction",
	"formidable": "opponent you're worried about; foreful, powerful",
	"prospect": "That which is expected",
	"conventional": "Customary; ordinary",
	"predictable": "Expected beforehand",
	"desperate": "Hopeless",
	"persuasion": "An active attempt to change attitudes.",
	"shrew": "clever, keen, astute, cunning",
	"stumble": "miss a step and fall or nearly fall",
	"contrary": "Opposite in nature, direction or meaning",
	"endorsement": "support; approval",
	"disgrace": "The loss of respect, honor, or esteem ; a person, act, or thing that causes shame, reproach, or dishonor",
	"perception": "Ability to see hear or become aware of something through the senses",
	"unleased": "released;set free",
	"futility": "uselessness",
	"trumph": "the act of victory",
	"contentment": "satisfaction",
	"scent": "a smell",
	"intimidated": "Frightened with threats",
	"lunatic": "An insane person",
	"fringe": "decorative edge of hanging threads; edge",
	"intent": "The purpose to use a particular means to bring about a certain result.",
	"malicious": "Intended to hurt or harm",
	"convict": "Judgment that someone is guilty of a crime.",
	"immence": "huge or massive",
	"reluctance": "Unwillingness; resisting",
	"drag": "A force that slows you down and resists motion",
	"deliberate": "to think over deeply",
	"affirmative": "An active effort to improve employment or education opportunities for minorities.",
	"reinforced": "to strengthen",
	"ensure": "Guarantee",
	"acknowledge": "To accept that something is true or exists, or to thank someone for helping you",
	"allocate": "To distribute",
	"assess": "Act of evaluation",
	"accomodation": "A state of balance between cooperation and conflict",
	"verge": "An edge, border or brink, To come close to the edge or border of",
	"awkward": "Clumsy",
	"extrovert": "An outgoing person",
	"coalition": "A combination, union, or merger for some specific purpose",
	"eternity": "Forever",
	"summon": "To call together, to send for or to request to appear",
	"relevant": "Important",
	"incumbent": "Necessary",
	"indeed": "really or certainly",
	"respository": "a place for storage; where things are kept",
	"defecation": "Elimination of undigested waste",
	"deception": "A trick; an attempt to make someone believe something that is not true",
	"accuse": "TO SAY THAT SOMEONE HAS DONE SOMETHING WRONG",
	"assault": "A physical attack or threat of attack",
	"retribution": "Punishment for bad behavior",
	"slander": "False speech intended to damage a person's reputation.",
	"perpetrator": "a person who commits a crime",
	"impunity": "Freedom from punishment",
	"impediments": "obstacles",
	"paradigm": "Model or pattern; worldview, set of shared assumptions, values, etc.",
	"accompany": "To go along with; to be together",
	"invincible": "Not able to be defeated, unbeatable",
	"repression": "An unconscious process that excludes unacceptable thoughts and feelings from awareness and memory",
	"deploy": "To position or arrange; to utilize; to form up",
	"conundrum": "riddle or puzzle with no solution",
	"retaliation": "revenge, punishment",
	"plight": "A difficult or dangerous condition or situation",
	"introspect": "An examination of one's own thoughts and feelings.",
	"spur": "False or deceitful",
	"bicker": "quarrel",
	"imperative": "Essential",
	"sort": "To arrange in an orderly manner",
	"fleet": "Ephemeral",
	"crew": "A group of people who have a mission.",
	"reckon": "expect, believe, or suppose",
	"anticipate": "to look forward to; to expect",
	"collaborating": "-Work together to find solution that makes everyone happy",
	"notorious": "Infamous",
	"sacrosanct": "Extremely holy",
	"jeopardises": "pose a threat to",
	"guise": "An external appearance",
	"monetary": "The management of the money supply and interest rates",
	"bludgeon": "A short heavy, thick club that has one end larger than the other",
	"abandon": "To leave",
	"wreak": "To bring about or inflict",
	"prurient": "having lustful desires or interests; tending to arouse sexual desires",
	"remorse": "Regret",
	"repent": "to feel sorry for what one has done or has failed to do",
	"tussle": "A fight",
	"sullenly": "sadly; in a depressing and gloomy way",
	"persistence": ", Determination .",
	"imminent": "About to happen",
	"insularity": "narrow-mindedness; isolation",
	"province": "Areas within a country or empire",
	"consisent": "in agreement",
	"unprecented": "never seen or done before",
	"turbelence": "state of violent agitation",
	"furious": "Angry",
	"contingent": "Dependent",
	"mocking": "Ridiculing",
	"prone": "Having a tendency to do somethin",
	"confront": "to meet face-to-face, especially as a challenge; come to grips with",
	"endorsement": "support; approval",
	"stereotype": "A conventional pattern, expression, character, or idea.",
	"rephrasing": "Helps to clarify",
	"dearth": "a lack, scarcity, inadequate supply; a famine",
	"lucid": "clear and easily understood",
	"wrapped": "covered",
	"compilation": "Collection of preexisting materials arrranged to form a new original work",
	"adversary": "An enemy or opponent",
	"intrigue": "A secret plot or scheme",
	"allegation": "An assertion made with little or no proof",
	"apprehensive": "fearful, worried",
	"scoured": "cleaned by hard rubbing with something rough",
	"archived": "to have filed or collected records or documents",
	"aide": "assistant; helper",
	"aptitude": "A natural talent",
	"floored": "greatly surprised",
	"probe": "to examine, investigate thoroughly; an investigation; a device used to explore or examine",
	"sore": "painful; hurting; tender",
	"amused": "entertained",
	"aplomb": "self-confidence",
	"unveil": "Visual",
	"bust": "To be noisily busy and in a hurry",
	"sulk": "sullen or moody",
	"weirdness": "being different out of the ordinary",
	"bluff": "To pretend to know more or feel more confident than one really does",
	"acquaitance": "A person you have met but do not know well.",
	"prosper": "wealth or success",
	"apathy": "lack of interest or emotion",
	"patrolled": "a person or group of people sent to keep watch over an area",
	"excrement": "waste matter (as urine or sweat but especially feces) discharged from the body",
	"vandalise": "deliberately damage or destroy something",
	"daubed": "smeared, applied, painted without skill, splattered",
	"garnered": "gathered and stored",
	"scuffle": "A fight or struggle.",
	"exacerbate": "To increase the severity, violence, or bitterness of; aggravate.",
	"incognizant": "not cognizant without knowledge or awareness; unaware (usually followed by ).",
	"sardonic": "Mocking, derisive, taunting, and stinging",
	"idiosyncratic": "Peculiar to one person; highly individualized",
	"senile": "characteristic of old age",
	"ephemeral": "lasting a short time",
	"annihilation": "total destruction",
	"obnoxious": "Adj. Very unpleasant; disgusting.",
	"strive": "To devote much energy or effort, try hard",
	"augument": "to make larger, increase",
	"oblivious": "Lacking conscious awareness; unmindful; unaware",
	"incoherrent": "Unclear or difficult to understand",
	"jubiliant": "happy; joyful",
	"eccentric": "A person that is peculiar or od",
	"exalted": "Raised or elevated, as in rank or character; of high statio",
	"idiotic": "insanely irresponsible",
	"adept": "Skilled; expert at",
	"slack": "lack of tension, lull, relaxation; sluggish",
	"replete": "abundantly supplied; complete",
	"rarified": "of high moral or intellectual value adj.",
	"nostalgic": "A bittersweet longing for things, persons, or situations of the past.",
	"dwindled": "V; To become smaller and smaller; shrink",
	"reverent": "expressing deep respect; worshipful",
	"chaos": "extreme confusion or disorder",
	"remedy": "cure; treatment; medicine",
	"disparate": "dissimilar",
	"dejected": "Depressed",
	"vivacity": "characterized by high spirits and animation",
	"vigour": "active strength or force",
	"jauntiness": "stylishness and liveliness in manner or appearance",
	"lethargy": "Lack of energy; sluggishness",
	"reclusive": "hermitlike; withdrawn from society",
	"gregarious": "outgoing; sociable",
	"benign": "Harmless",
	"authentic": "Genuine and true, not fake",
	"absurd": "nonsensical,unreasonable",
	"betray": "be unfaithful; reveal",
	"lofty": "very high; noble",
	"splendid": "brilliant; glorious; magnificent; grand; fine; excellent.",
	"sturdy": "strong",
	"meritonious": "worthy, deserving recognition and praise",
	"Innovation": "Change; Introducing of something new",
	"Demise": "A death, especially of a person in a lofty positing",
	"Unprecedented": "Never done or known before; without previous example",
	"reluctant": "Hesitant",
	"impeccable": "faultless",
	"cobbler": "a person who makes or repairs shoes",
	"Reckoning": "reputation",
	"Spurious": "false; fake; not genuine.",
	"Seer": "an eyewitness; someone who foretells the future; prophet, soothsayer",
	"Indigenous": "Native to a certain area",
	"Epitome": "A perfect example",
	"Exemplary": "outstaning",
	"Abused": "over use or misused"
}
module.exports = intermediateDict;